schema_version: 1

context:
  name: mjlab
  version: "1.3.0"
  build_number: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mujocolab/mjlab/archive/refs/tags/v${{ version }}.zip
  sha256: dcbc8ff6a575b6bdf66ccf1272ec7cbebcf447f9da66316de1f01a06e815b68b
  patches:
    - fix-segmentation-vec2i.patch
    - fix-multiccd-enable-flag.patch

build:
  number: ${{ build_number }}
  script:
    - if: not linux
      then:
        - sed -i '' "s/\"torchrunx\([^\"]*\)\"/\"torchrunx\1; sys_platform == 'linux'\"/" pyproject.toml
        - cat pyproject.toml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - python >=${{ python_min }}
    - prettytable
    - tqdm
    - tyro >=1.0.1
    - pytorch >=2.7.0
    - if: linux
      then:
        - __linux
        - torchrunx >=0.3.4
    - warp-lang >=1.12.0
    - mujoco-warp >=3.7.0.1
    - mujoco >=3.7.0
    - trimesh >=4.8.3
    - viser >=1.0.26
    - mjviser >=0.0.11
    - mediapy >=1.2.6
    - imageio-ffmpeg
    - tensordict
    - rsl-rl-lib ==5.0.1
    - tensorboard >=2.20.0
    - onnxscript >=0.5.4
    - wandb >=0.22.3
  run_constraints:
    - if: not linux
      then:
        - __linux ==0.0.0

tests:
  - python:
      imports:
        - mjlab
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pytest tests/
    files:
      source:
        - pyproject.toml
        - src/mjlab/asset_zoo
        - src/mjlab/scripts
        - scripts/
        - tests/
    requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
        - scipy

about:
  homepage: https://mujocolab.github.io/mjlab/
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/mujocolab/mjlab
  summary: Isaac Lab API, powered by MuJoCo-Warp, for RL and robotics research.

extra:
  recipe-maintainers:
    - kevinzakka
    - diegoferigo
